name: 'Install Kustomize'
description: 'Install Kustomize and add it to the $PATH'
inputs:
  kustomize-version:
    description: 'The kustomize version to download (if necessary) and use'
    required: false
runs:
  using: 'composite'
  steps:
  - run: curl -O "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
    shell: bash
  - run: bash ./install_kustomize.sh ${{ inputs.kustomize-version }} /tmp
    shell: bash
  - run: sudo mv /tmp/kustomize /usr/local/bin/kustomize && chmod +x /usr/local/bin/kustomize
    shell: bash
  - run: rm -f ./install_kustomize.sh
    shell: bash
