name: 'Setup Kustomize'
description: 'Setup Kustomize and add it to the PATH'
inputs:
  kustomize-version:
    description: 'The kustomize version to download (if necessary) and use'
    required: false
runs:
  using: 'composite'
  steps:
  - run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash ${{ inputs.kustomize-version }}
    shell: bash
  - run: mv kustomize /usr/local/bin/kustomize && chmod +x /usr/local/bin/kustomize
    shell: bash
