name: 'Setup Kustomize'
description: 'Setup Kustomize and add it to the PATH'
inputs:
  kustomize-version:
    description: 'The kustomize version to download (if necessary) and use'
    required: false
runs:
  using: 'composite'
  steps:
  - run: install.sh ${{ inputs.kustomize-version }}
    shell: bash
